export const upcomingEventsData=[
    {
        id:1,
        date:"Monday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:2,
        date:"Friday, 19 March 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:3,
        date:"Tuesday, 11 May 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:false,
    },
    {
        id:4,
        date:"Thursday, 15 September 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:false,
    },
    {
        id:5,
        date:"Thursday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:6,
        date:"Wednesday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:false,
    },
    {
        id:7,
        date:"Friday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:8,
        date:"Monday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:9,
        date:"Tuesday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:true,
    },
    {
        id:10,
        date:"Wednesday, 15 February 2020",
        desc:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor",
        name:"Speaker Name",
        accuracy:false,
    },
]